version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_FILE=/app/data/catalog.db
      - NODE_ENV=production
    volumes:
      - ./data:/app/data